server:
  port: 8080

faucet:
  private_key: 
  rpc_url: 
  faucet_amount: 

log:
  level: 
  file: 

rpc:
  EthSepolia: 
  MonadDevnet: 
  MonadDevnetExplorer: 
  ZeroTestnet: 
  ZeroTestnetExplorer: 

database:
  host: 
  port:
  user: 
  password: 
  dbname: 
  sslmode: 

